require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Max: 160
  Exclude:
    - config/routes.rb

Layout/SpaceBeforeFirstArg:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/ClassAndModuleChildren:
  Include:
    - lib/**/*.rb

Style/CollectionMethods:
  PreferredMethods:
    find: "detect"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
